---
# tasks file for cfme-ose-provider

- name: Add Openshift Containers Provider to ManageIQ
  manageiq_provider:
    name: 'Openshift01'
    provider_type: 'openshift-enterprise'
    state: 'present'
    provider_api_hostname: 'openshift-master.strategicdesign.io'
    provider_api_port: '443'
    provider_api_auth_token: "{{ token }}"
    metrics: false
    miq_url: "{{ miq_url }}"
    miq_username: 'admin'
    miq_password: 'smartvm'
    miq_verify_ssl: false
    provider_verify_ssl: false
  register: result
  ignore_errors: yes

- debug: var=result
